# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vavabot_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(716, 461)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../vavabot_delta_hedge_1_0/icon_noctuline_wall_e_eve_hedge.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_credentials = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tab_credentials.setFont(font)
        self.tab_credentials.setObjectName("tab_credentials")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_credentials)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2_credentials = QtWidgets.QFrame(self.tab_credentials)
        self.frame_2_credentials.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_credentials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_credentials.setObjectName("frame_2_credentials")
        self.label = QtWidgets.QLabel(self.frame_2_credentials)
        self.label.setGeometry(QtCore.QRect(60, 20, 111, 31))
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.lineEdit_api_key_new = QtWidgets.QLineEdit(self.frame_2_credentials)
        self.lineEdit_api_key_new.setGeometry(QtCore.QRect(10, 100, 171, 31))
        self.lineEdit_api_key_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_api_key_new.setObjectName("lineEdit_api_key_new")
        self.label_2 = QtWidgets.QLabel(self.frame_2_credentials)
        self.label_2.setGeometry(QtCore.QRect(190, 70, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2_credentials)
        self.label_3.setGeometry(QtCore.QRect(190, 110, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_api_secret_saved = QtWidgets.QLineEdit(self.frame_2_credentials)
        self.lineEdit_api_secret_saved.setEnabled(True)
        self.lineEdit_api_secret_saved.setGeometry(QtCore.QRect(260, 60, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_api_secret_saved.setFont(font)
        self.lineEdit_api_secret_saved.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_api_secret_saved.setText("")
        self.lineEdit_api_secret_saved.setReadOnly(True)
        self.lineEdit_api_secret_saved.setObjectName("lineEdit_api_secret_saved")
        self.lineEdit_api_secret_new = QtWidgets.QLineEdit(self.frame_2_credentials)
        self.lineEdit_api_secret_new.setGeometry(QtCore.QRect(260, 100, 391, 31))
        self.lineEdit_api_secret_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_api_secret_new.setClearButtonEnabled(False)
        self.lineEdit_api_secret_new.setObjectName("lineEdit_api_secret_new")
        self.label_4 = QtWidgets.QLabel(self.frame_2_credentials)
        self.label_4.setGeometry(QtCore.QRect(350, 20, 111, 31))
        self.label_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.radioButton_testnet_true = QtWidgets.QRadioButton(self.frame_2_credentials)
        self.radioButton_testnet_true.setGeometry(QtCore.QRect(30, 280, 351, 17))
        self.radioButton_testnet_true.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.radioButton_testnet_true.setObjectName("radioButton_testnet_true")
        self.radioButton_2_testnet_false = QtWidgets.QRadioButton(self.frame_2_credentials)
        self.radioButton_2_testnet_false.setGeometry(QtCore.QRect(30, 310, 321, 17))
        self.radioButton_2_testnet_false.setObjectName("radioButton_2_testnet_false")
        self.label_5 = QtWidgets.QLabel(self.frame_2_credentials)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 201, 21))
        self.label_5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.pushButton_submit_new_credintals = QtWidgets.QPushButton(self.frame_2_credentials)
        self.pushButton_submit_new_credintals.setGeometry(QtCore.QRect(430, 150, 231, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_submit_new_credintals.setFont(font)
        self.pushButton_submit_new_credintals.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_submit_new_credintals.setObjectName("pushButton_submit_new_credintals")
        self.lineEdit_api_key_saved = QtWidgets.QLineEdit(self.frame_2_credentials)
        self.lineEdit_api_key_saved.setEnabled(True)
        self.lineEdit_api_key_saved.setGeometry(QtCore.QRect(10, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_api_key_saved.setFont(font)
        self.lineEdit_api_key_saved.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_api_key_saved.setText("")
        self.lineEdit_api_key_saved.setReadOnly(True)
        self.lineEdit_api_key_saved.setObjectName("lineEdit_api_key_saved")
        self.lineEdit_testenet_true_or_false_satatus = QtWidgets.QLineEdit(self.frame_2_credentials)
        self.lineEdit_testenet_true_or_false_satatus.setGeometry(QtCore.QRect(230, 340, 113, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_testenet_true_or_false_satatus.setFont(font)
        self.lineEdit_testenet_true_or_false_satatus.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_testenet_true_or_false_satatus.setToolTipDuration(-1)
        self.lineEdit_testenet_true_or_false_satatus.setStyleSheet("color: rgb(255, 0, 0);")
        self.lineEdit_testenet_true_or_false_satatus.setText("")
        self.lineEdit_testenet_true_or_false_satatus.setCursorPosition(0)
        self.lineEdit_testenet_true_or_false_satatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_testenet_true_or_false_satatus.setDragEnabled(False)
        self.lineEdit_testenet_true_or_false_satatus.setReadOnly(True)
        self.lineEdit_testenet_true_or_false_satatus.setObjectName("lineEdit_testenet_true_or_false_satatus")
        self.label_7 = QtWidgets.QLabel(self.frame_2_credentials)
        self.label_7.setGeometry(QtCore.QRect(30, 339, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.line_4 = QtWidgets.QFrame(self.frame_2_credentials)
        self.line_4.setGeometry(QtCore.QRect(10, 220, 651, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.frame_2_credentials, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_credentials, "")
        self.tab_instruments = QtWidgets.QWidget()
        self.tab_instruments.setObjectName("tab_instruments")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_instruments)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.tab_instruments)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setInputMethodHints(QtCore.Qt.ImhDate)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_submit_new_instruments = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_submit_new_instruments.setGeometry(QtCore.QRect(420, 110, 231, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_submit_new_instruments.setFont(font)
        self.pushButton_submit_new_instruments.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_submit_new_instruments.setObjectName("pushButton_submit_new_instruments")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(10, 110, 291, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.textEdit_instruments_saved = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_instruments_saved.setGeometry(QtCore.QRect(10, 130, 291, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_instruments_saved.setFont(font)
        self.textEdit_instruments_saved.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_instruments_saved.setReadOnly(True)
        self.textEdit_instruments_saved.setObjectName("textEdit_instruments_saved")
        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setGeometry(QtCore.QRect(0, 200, 661, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 651, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_o_or_f_instrumet1 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.lineEdit_o_or_f_instrumet1.setMinimumSize(QtCore.QSize(127, 18))
        self.lineEdit_o_or_f_instrumet1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_o_or_f_instrumet1.setObjectName("lineEdit_o_or_f_instrumet1")
        self.lineEdit_o_or_f_instrumet1.addItem("")
        self.horizontalLayout.addWidget(self.lineEdit_o_or_f_instrumet1)
        self.lineEdit_currency_instrumet1 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.lineEdit_currency_instrumet1.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_currency_instrumet1.setObjectName("lineEdit_currency_instrumet1")
        self.lineEdit_currency_instrumet1.addItem("")
        self.lineEdit_currency_instrumet1.addItem("")
        self.lineEdit_currency_instrumet1.addItem("")
        self.horizontalLayout.addWidget(self.lineEdit_currency_instrumet1)
        self.lineEdit_maturity_instrumet1 = QtWidgets.QDateEdit(self.horizontalLayoutWidget)
        self.lineEdit_maturity_instrumet1.setMinimumSize(QtCore.QSize(64, 0))
        self.lineEdit_maturity_instrumet1.setStyleSheet("")
        self.lineEdit_maturity_instrumet1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_maturity_instrumet1.setCalendarPopup(True)
        self.lineEdit_maturity_instrumet1.setTimeSpec(QtCore.Qt.LocalTime)
        self.lineEdit_maturity_instrumet1.setDate(QtCore.QDate(2021, 1, 1))
        self.lineEdit_maturity_instrumet1.setObjectName("lineEdit_maturity_instrumet1")
        self.horizontalLayout.addWidget(self.lineEdit_maturity_instrumet1)
        self.checkBox_perpetual_1 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_perpetual_1.setFont(font)
        self.checkBox_perpetual_1.setObjectName("checkBox_perpetual_1")
        self.horizontalLayout.addWidget(self.checkBox_perpetual_1)
        self.lineEdit_o_or_f_instrumet1_3 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.lineEdit_o_or_f_instrumet1_3.setMinimumSize(QtCore.QSize(127, 18))
        self.lineEdit_o_or_f_instrumet1_3.setObjectName("lineEdit_o_or_f_instrumet1_3")
        self.lineEdit_o_or_f_instrumet1_3.addItem("")
        self.lineEdit_o_or_f_instrumet1_3.addItem("")
        self.horizontalLayout.addWidget(self.lineEdit_o_or_f_instrumet1_3)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 651, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 250, 218, 111))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setHorizontalSpacing(9)
        self.formLayout_3.setVerticalSpacing(1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2.setObjectName("lineEdit_currency_exchange_rate_for_upper_and_lower1_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2)
        self.lineEdit_currency_exchange_rate_upper1_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_currency_exchange_rate_upper1_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_currency_exchange_rate_upper1_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_currency_exchange_rate_upper1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_currency_exchange_rate_upper1_2.setObjectName("lineEdit_currency_exchange_rate_upper1_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_currency_exchange_rate_upper1_2)
        self.lineEdit_currency_exchange_rate_lower1_3 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_currency_exchange_rate_lower1_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_currency_exchange_rate_lower1_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_currency_exchange_rate_lower1_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_currency_exchange_rate_lower1_3.setObjectName("lineEdit_currency_exchange_rate_lower1_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_currency_exchange_rate_lower1_3)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_o_or_f_instrumet1_5 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.lineEdit_o_or_f_instrumet1_5.setMinimumSize(QtCore.QSize(0, 18))
        self.lineEdit_o_or_f_instrumet1_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_o_or_f_instrumet1_5.setObjectName("lineEdit_o_or_f_instrumet1_5")
        self.lineEdit_o_or_f_instrumet1_5.addItem("")
        self.lineEdit_o_or_f_instrumet1_5.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_o_or_f_instrumet1_5)
        self.lineEdit_o_or_f_instrumet1_8 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.lineEdit_o_or_f_instrumet1_8.setMinimumSize(QtCore.QSize(135, 18))
        self.lineEdit_o_or_f_instrumet1_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_o_or_f_instrumet1_8.setObjectName("lineEdit_o_or_f_instrumet1_8")
        self.lineEdit_o_or_f_instrumet1_8.addItem("")
        self.lineEdit_o_or_f_instrumet1_8.addItem("")
        self.lineEdit_o_or_f_instrumet1_8.addItem("")
        self.lineEdit_o_or_f_instrumet1_8.addItem("")
        self.lineEdit_o_or_f_instrumet1_8.addItem("")
        self.lineEdit_o_or_f_instrumet1_8.addItem("")
        self.lineEdit_o_or_f_instrumet1_8.addItem("")
        self.lineEdit_o_or_f_instrumet1_8.addItem("")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lineEdit_o_or_f_instrumet1_8)
        self.lineEdit_o_or_f_instrumet1_9 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.lineEdit_o_or_f_instrumet1_9.setMinimumSize(QtCore.QSize(135, 18))
        self.lineEdit_o_or_f_instrumet1_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_o_or_f_instrumet1_9.setObjectName("lineEdit_o_or_f_instrumet1_9")
        self.lineEdit_o_or_f_instrumet1_9.addItem("")
        self.lineEdit_o_or_f_instrumet1_9.addItem("")
        self.lineEdit_o_or_f_instrumet1_9.addItem("")
        self.lineEdit_o_or_f_instrumet1_9.addItem("")
        self.lineEdit_o_or_f_instrumet1_9.addItem("")
        self.lineEdit_o_or_f_instrumet1_9.addItem("")
        self.lineEdit_o_or_f_instrumet1_9.addItem("")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lineEdit_o_or_f_instrumet1_9)
        self.lineEdit_o_or_f_instrumet1_10 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.lineEdit_o_or_f_instrumet1_10.setMinimumSize(QtCore.QSize(135, 18))
        self.lineEdit_o_or_f_instrumet1_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_o_or_f_instrumet1_10.setObjectName("lineEdit_o_or_f_instrumet1_10")
        self.lineEdit_o_or_f_instrumet1_10.addItem("")
        self.lineEdit_o_or_f_instrumet1_10.addItem("")
        self.lineEdit_o_or_f_instrumet1_10.addItem("")
        self.lineEdit_o_or_f_instrumet1_10.addItem("")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lineEdit_o_or_f_instrumet1_10)
        self.lineEdit_currency_exchange_rate_lower1_4 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_currency_exchange_rate_lower1_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_currency_exchange_rate_lower1_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_currency_exchange_rate_lower1_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_currency_exchange_rate_lower1_4.setObjectName("lineEdit_currency_exchange_rate_lower1_4")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_currency_exchange_rate_lower1_4)
        self.textEdit_instruments_saved_2 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_instruments_saved_2.setGeometry(QtCore.QRect(460, 240, 201, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_instruments_saved_2.setFont(font)
        self.textEdit_instruments_saved_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_instruments_saved_2.setReadOnly(True)
        self.textEdit_instruments_saved_2.setObjectName("textEdit_instruments_saved_2")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(460, 220, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.pushButton_submit_new_instruments_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_submit_new_instruments_2.setGeometry(QtCore.QRect(250, 300, 181, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_submit_new_instruments_2.setFont(font)
        self.pushButton_submit_new_instruments_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_submit_new_instruments_2.setObjectName("pushButton_submit_new_instruments_2")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(0, 220, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 60, 651, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_o_or_f_instrumet1_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.lineEdit_o_or_f_instrumet1_2.setMinimumSize(QtCore.QSize(127, 18))
        self.lineEdit_o_or_f_instrumet1_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_o_or_f_instrumet1_2.setObjectName("lineEdit_o_or_f_instrumet1_2")
        self.lineEdit_o_or_f_instrumet1_2.addItem("")
        self.horizontalLayout_2.addWidget(self.lineEdit_o_or_f_instrumet1_2)
        self.lineEdit_currency_instrumet1_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.lineEdit_currency_instrumet1_2.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_currency_instrumet1_2.setObjectName("lineEdit_currency_instrumet1_2")
        self.lineEdit_currency_instrumet1_2.addItem("")
        self.lineEdit_currency_instrumet1_2.addItem("")
        self.lineEdit_currency_instrumet1_2.addItem("")
        self.horizontalLayout_2.addWidget(self.lineEdit_currency_instrumet1_2)
        self.lineEdit_maturity_instrumet1_2 = QtWidgets.QDateEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_maturity_instrumet1_2.setMinimumSize(QtCore.QSize(64, 0))
        self.lineEdit_maturity_instrumet1_2.setStyleSheet("")
        self.lineEdit_maturity_instrumet1_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_maturity_instrumet1_2.setCalendarPopup(True)
        self.lineEdit_maturity_instrumet1_2.setTimeSpec(QtCore.Qt.LocalTime)
        self.lineEdit_maturity_instrumet1_2.setDate(QtCore.QDate(2021, 1, 1))
        self.lineEdit_maturity_instrumet1_2.setObjectName("lineEdit_maturity_instrumet1_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_maturity_instrumet1_2)
        self.checkBox_perpetual_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_perpetual_2.setFont(font)
        self.checkBox_perpetual_2.setObjectName("checkBox_perpetual_2")
        self.horizontalLayout_2.addWidget(self.checkBox_perpetual_2)
        self.lineEdit_o_or_f_instrumet1_4 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.lineEdit_o_or_f_instrumet1_4.setMinimumSize(QtCore.QSize(127, 18))
        self.lineEdit_o_or_f_instrumet1_4.setObjectName("lineEdit_o_or_f_instrumet1_4")
        self.lineEdit_o_or_f_instrumet1_4.addItem("")
        self.lineEdit_o_or_f_instrumet1_4.addItem("")
        self.horizontalLayout_2.addWidget(self.lineEdit_o_or_f_instrumet1_4)
        self.label_10.raise_()
        self.label_17.raise_()
        self.textEdit_instruments_saved.raise_()
        self.line_5.raise_()
        self.horizontalLayoutWidget.raise_()
        self.pushButton_submit_new_instruments.raise_()
        self.label_8.raise_()
        self.formLayoutWidget_3.raise_()
        self.textEdit_instruments_saved_2.raise_()
        self.label_18.raise_()
        self.pushButton_submit_new_instruments_2.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.gridLayout_6.addWidget(self.frame_2, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_instruments, "")
        self.tab_run_trading = QtWidgets.QWidget()
        self.tab_run_trading.setObjectName("tab_run_trading")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_run_trading)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3_run_trade = QtWidgets.QFrame(self.tab_run_trading)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_3_run_trade.setFont(font)
        self.frame_3_run_trade.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3_run_trade.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3_run_trade.setObjectName("frame_3_run_trade")
        self.textEdit_monitor = QtWidgets.QTextEdit(self.frame_3_run_trade)
        self.textEdit_monitor.setGeometry(QtCore.QRect(3, 170, 511, 201))
        self.textEdit_monitor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_monitor.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.textEdit_monitor.setUndoRedoEnabled(True)
        self.textEdit_monitor.setReadOnly(True)
        self.textEdit_monitor.setObjectName("textEdit_monitor")
        self.label_41 = QtWidgets.QLabel(self.frame_3_run_trade)
        self.label_41.setGeometry(QtCore.QRect(10, 140, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_41.setObjectName("label_41")
        self.pushButton_start_trading = QtWidgets.QPushButton(self.frame_3_run_trade)
        self.pushButton_start_trading.setGeometry(QtCore.QRect(0, 40, 121, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_start_trading.setFont(font)
        self.pushButton_start_trading.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(49, 148, 72);")
        self.pushButton_start_trading.setObjectName("pushButton_start_trading")
        self.pushButton_start_print_loglog = QtWidgets.QPushButton(self.frame_3_run_trade)
        self.pushButton_start_print_loglog.setGeometry(QtCore.QRect(130, 110, 75, 23))
        self.pushButton_start_print_loglog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_start_print_loglog.setCheckable(False)
        self.pushButton_start_print_loglog.setObjectName("pushButton_start_print_loglog")
        self.lineEdit_24_btc_index = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_24_btc_index.setGeometry(QtCore.QRect(360, 0, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_24_btc_index.setFont(font)
        self.lineEdit_24_btc_index.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_24_btc_index.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_24_btc_index.setReadOnly(True)
        self.lineEdit_24_btc_index.setObjectName("lineEdit_24_btc_index")
        self.label_22 = QtWidgets.QLabel(self.frame_3_run_trade)
        self.label_22.setGeometry(QtCore.QRect(290, 0, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayoutWidget_10 = QtWidgets.QWidget(self.frame_3_run_trade)
        self.formLayoutWidget_10.setGeometry(QtCore.QRect(520, 20, 151, 162))
        self.formLayoutWidget_10.setObjectName("formLayoutWidget_10")
        self.formLayout_10 = QtWidgets.QFormLayout(self.formLayoutWidget_10)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setHorizontalSpacing(4)
        self.formLayout_10.setVerticalSpacing(0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_24.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_24)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_26.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_26.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_26.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_26)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_25.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_25.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_25)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.label_30.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_27.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_27.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_27.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_27.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_27.setReadOnly(True)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_27)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.label_11.setObjectName("label_11")
        self.formLayout_10.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_10.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.label_12.setObjectName("label_12")
        self.formLayout_10.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_10.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.label_13.setObjectName("label_13")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.label_14.setObjectName("label_14")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_58.setGeometry(QtCore.QRect(460, 0, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_58.setFont(font)
        self.lineEdit_58.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_58.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_58.setReadOnly(True)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.pushButton = QtWidgets.QPushButton(self.frame_3_run_trade)
        self.pushButton.setGeometry(QtCore.QRect(10, 130, 91, 31))
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit.setGeometry(QtCore.QRect(520, 0, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_6.setGeometry(QtCore.QRect(520, 190, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayoutWidget_11 = QtWidgets.QWidget(self.frame_3_run_trade)
        self.formLayoutWidget_11.setGeometry(QtCore.QRect(520, 210, 151, 162))
        self.formLayoutWidget_11.setObjectName("formLayoutWidget_11")
        self.formLayout_11 = QtWidgets.QFormLayout(self.formLayoutWidget_11)
        self.formLayout_11.setContentsMargins(0, 0, 0, 0)
        self.formLayout_11.setHorizontalSpacing(4)
        self.formLayout_11.setVerticalSpacing(0)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_28.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_28.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_28.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_28.setReadOnly(True)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_28)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_29.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_29.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_29.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_29)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_30.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_30.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_30.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_30.setReadOnly(True)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_30)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.label_31.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout_11.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_31.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_31.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_31.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_31.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_31.setReadOnly(True)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.formLayout_11.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_31)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.label_19.setObjectName("label_19")
        self.formLayout_11.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_11.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.label_20.setObjectName("label_20")
        self.formLayout_11.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_11.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.label_21.setObjectName("label_21")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.label_23.setObjectName("label_23")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.label_24 = QtWidgets.QLabel(self.frame_3_run_trade)
        self.label_24.setGeometry(QtCore.QRect(10, 2, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_29 = QtWidgets.QLabel(self.frame_3_run_trade)
        self.label_29.setGeometry(QtCore.QRect(80, 2, 21, 21))
        self.label_29.setText("")
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.pushButton_stop_arbitrage = QtWidgets.QPushButton(self.frame_3_run_trade)
        self.pushButton_stop_arbitrage.setGeometry(QtCore.QRect(130, 40, 75, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_stop_arbitrage.setFont(font)
        self.pushButton_stop_arbitrage.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_stop_arbitrage.setStyleSheet("color: rgb(255, 0, 0);")
        self.pushButton_stop_arbitrage.setCheckable(False)
        self.pushButton_stop_arbitrage.setObjectName("pushButton_stop_arbitrage")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_11.setEnabled(True)
        self.lineEdit_11.setGeometry(QtCore.QRect(240, 20, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_12.setGeometry(QtCore.QRect(240, 40, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_32.setGeometry(QtCore.QRect(450, 20, 55, 20))
        self.lineEdit_32.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_32.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_32.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_32.setReadOnly(True)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_33.setGeometry(QtCore.QRect(450, 40, 55, 20))
        self.lineEdit_33.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_33.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_33.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_33.setReadOnly(True)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_13.setGeometry(QtCore.QRect(240, 60, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_14.setGeometry(QtCore.QRect(240, 80, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_34.setGeometry(QtCore.QRect(450, 60, 55, 20))
        self.lineEdit_34.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_34.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_34.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_34.setReadOnly(True)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_35.setGeometry(QtCore.QRect(450, 80, 55, 20))
        self.lineEdit_35.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_35.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_35.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_35.setReadOnly(True)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.label_32 = QtWidgets.QLabel(self.frame_3_run_trade)
        self.label_32.setGeometry(QtCore.QRect(51, 95, 21, 21))
        self.label_32.setText("")
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3_run_trade)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 10, 16, 21))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_15.setGeometry(QtCore.QRect(240, 100, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_36.setGeometry(QtCore.QRect(450, 100, 55, 20))
        self.lineEdit_36.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_36.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_36.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_36.setReadOnly(True)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.checkBox_autoScrollBar = QtWidgets.QCheckBox(self.frame_3_run_trade)
        self.checkBox_autoScrollBar.setGeometry(QtCore.QRect(410, 150, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_autoScrollBar.setFont(font)
        self.checkBox_autoScrollBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_autoScrollBar.setObjectName("checkBox_autoScrollBar")
        self.label_41.raise_()
        self.label_22.raise_()
        self.textEdit_monitor.raise_()
        self.pushButton_start_print_loglog.raise_()
        self.lineEdit_24_btc_index.raise_()
        self.formLayoutWidget_10.raise_()
        self.lineEdit_58.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.lineEdit_6.raise_()
        self.formLayoutWidget_11.raise_()
        self.label_24.raise_()
        self.label_29.raise_()
        self.lineEdit_11.raise_()
        self.lineEdit_12.raise_()
        self.lineEdit_32.raise_()
        self.lineEdit_33.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_14.raise_()
        self.lineEdit_34.raise_()
        self.lineEdit_35.raise_()
        self.pushButton_start_trading.raise_()
        self.pushButton_stop_arbitrage.raise_()
        self.label_32.raise_()
        self.pushButton_2.raise_()
        self.lineEdit_15.raise_()
        self.lineEdit_36.raise_()
        self.checkBox_autoScrollBar.raise_()
        self.gridLayout_4.addWidget(self.frame_3_run_trade, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_run_trading, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_2_credentials_2 = QtWidgets.QFrame(self.tab)
        self.frame_2_credentials_2.setGeometry(QtCore.QRect(10, 10, 671, 371))
        self.frame_2_credentials_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_credentials_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_credentials_2.setObjectName("frame_2_credentials_2")
        self.label_33 = QtWidgets.QLabel(self.frame_2_credentials_2)
        self.label_33.setGeometry(QtCore.QRect(30, 100, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_33.setFont(font)
        self.label_33.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_33.setObjectName("label_33")
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.checkBox_perpetual_1.clicked['bool'].connect(self.lineEdit_maturity_instrumet1.setDisabled)
        self.checkBox_perpetual_2.clicked['bool'].connect(self.lineEdit_maturity_instrumet1_2.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.lineEdit_api_key_new)
        MainWindow.setTabOrder(self.lineEdit_api_key_new, self.lineEdit_api_secret_new)
        MainWindow.setTabOrder(self.lineEdit_api_secret_new, self.radioButton_testnet_true)
        MainWindow.setTabOrder(self.radioButton_testnet_true, self.radioButton_2_testnet_false)
        MainWindow.setTabOrder(self.radioButton_2_testnet_false, self.pushButton_submit_new_credintals)
        MainWindow.setTabOrder(self.pushButton_submit_new_credintals, self.lineEdit_currency_instrumet1)
        MainWindow.setTabOrder(self.lineEdit_currency_instrumet1, self.lineEdit_maturity_instrumet1)
        MainWindow.setTabOrder(self.lineEdit_maturity_instrumet1, self.checkBox_perpetual_1)
        MainWindow.setTabOrder(self.checkBox_perpetual_1, self.lineEdit_o_or_f_instrumet1_3)
        MainWindow.setTabOrder(self.lineEdit_o_or_f_instrumet1_3, self.lineEdit_currency_instrumet1_2)
        MainWindow.setTabOrder(self.lineEdit_currency_instrumet1_2, self.lineEdit_maturity_instrumet1_2)
        MainWindow.setTabOrder(self.lineEdit_maturity_instrumet1_2, self.checkBox_perpetual_2)
        MainWindow.setTabOrder(self.checkBox_perpetual_2, self.lineEdit_o_or_f_instrumet1_4)
        MainWindow.setTabOrder(self.lineEdit_o_or_f_instrumet1_4, self.pushButton_submit_new_instruments)
        MainWindow.setTabOrder(self.pushButton_submit_new_instruments, self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2)
        MainWindow.setTabOrder(self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2, self.lineEdit_o_or_f_instrumet1_5)
        MainWindow.setTabOrder(self.lineEdit_o_or_f_instrumet1_5, self.lineEdit_o_or_f_instrumet1_9)
        MainWindow.setTabOrder(self.lineEdit_o_or_f_instrumet1_9, self.lineEdit_currency_exchange_rate_upper1_2)
        MainWindow.setTabOrder(self.lineEdit_currency_exchange_rate_upper1_2, self.lineEdit_o_or_f_instrumet1_8)
        MainWindow.setTabOrder(self.lineEdit_o_or_f_instrumet1_8, self.lineEdit_currency_exchange_rate_lower1_3)
        MainWindow.setTabOrder(self.lineEdit_currency_exchange_rate_lower1_3, self.lineEdit_o_or_f_instrumet1_10)
        MainWindow.setTabOrder(self.lineEdit_o_or_f_instrumet1_10, self.lineEdit_currency_exchange_rate_lower1_4)
        MainWindow.setTabOrder(self.lineEdit_currency_exchange_rate_lower1_4, self.pushButton_submit_new_instruments_2)
        MainWindow.setTabOrder(self.pushButton_submit_new_instruments_2, self.pushButton_start_trading)
        MainWindow.setTabOrder(self.pushButton_start_trading, self.pushButton_stop_arbitrage)
        MainWindow.setTabOrder(self.pushButton_stop_arbitrage, self.checkBox_autoScrollBar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VavaBot - Arbitrage beta 1.1"))
        self.label.setText(_translate("MainWindow", "API Key"))
        self.label_2.setText(_translate("MainWindow", "Saved"))
        self.label_3.setText(_translate("MainWindow", "Update"))
        self.label_4.setText(_translate("MainWindow", "API Secret"))
        self.radioButton_testnet_true.setText(_translate("MainWindow", "TEST ACCOUNT"))
        self.radioButton_2_testnet_false.setText(_translate("MainWindow", "REAL ACCOUNT"))
        self.label_5.setText(_translate("MainWindow", "Select acoount mode:"))
        self.pushButton_submit_new_credintals.setText(_translate("MainWindow", "SUBMIT new Credentials"))
        self.label_7.setText(_translate("MainWindow", "Current Status account mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_credentials), _translate("MainWindow", "Credentials"))
        self.pushButton_submit_new_instruments.setText(_translate("MainWindow", "UPDATE Instrument"))
        self.label_17.setText(_translate("MainWindow", "Check Saved Instruments:"))
        self.lineEdit_o_or_f_instrumet1.setItemText(0, _translate("MainWindow", "Future "))
        self.lineEdit_currency_instrumet1.setItemText(0, _translate("MainWindow", "Set BTC or ETH:"))
        self.lineEdit_currency_instrumet1.setItemText(1, _translate("MainWindow", "BTC"))
        self.lineEdit_currency_instrumet1.setItemText(2, _translate("MainWindow", "ETH"))
        self.lineEdit_maturity_instrumet1.setDisplayFormat(_translate("MainWindow", "dMMMyy"))
        self.checkBox_perpetual_1.setText(_translate("MainWindow", "PERPETUAL"))
        self.lineEdit_o_or_f_instrumet1_3.setItemText(0, _translate("MainWindow", "Buy"))
        self.lineEdit_o_or_f_instrumet1_3.setItemText(1, _translate("MainWindow", "Sell"))
        self.label_8.setText(_translate("MainWindow", "Arbitrage Instruments:"))
        self.label_9.setText(_translate("MainWindow", "Total Amount (USD):"))
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2.setText(_translate("MainWindow", "0"))
        self.lineEdit_currency_exchange_rate_upper1_2.setText(_translate("MainWindow", "300"))
        self.lineEdit_currency_exchange_rate_lower1_3.setText(_translate("MainWindow", "0.1"))
        self.label_6.setText(_translate("MainWindow", "Positions with same size in:"))
        self.lineEdit_o_or_f_instrumet1_5.setItemText(0, _translate("MainWindow", "USD"))
        self.lineEdit_o_or_f_instrumet1_5.setItemText(1, _translate("MainWindow", "BTC/ETH"))
        self.lineEdit_o_or_f_instrumet1_8.setItemText(0, _translate("MainWindow", "Set Exit Position"))
        self.lineEdit_o_or_f_instrumet1_8.setItemText(1, _translate("MainWindow", "Profit in % > "))
        self.lineEdit_o_or_f_instrumet1_8.setItemText(2, _translate("MainWindow", "Difference  in % > "))
        self.lineEdit_o_or_f_instrumet1_8.setItemText(3, _translate("MainWindow", "Difference in % < "))
        self.lineEdit_o_or_f_instrumet1_8.setItemText(4, _translate("MainWindow", "Difference in USD > "))
        self.lineEdit_o_or_f_instrumet1_8.setItemText(5, _translate("MainWindow", "Difference in USD < "))
        self.lineEdit_o_or_f_instrumet1_8.setItemText(6, _translate("MainWindow", "Dif. Annualized Premium > "))
        self.lineEdit_o_or_f_instrumet1_8.setItemText(7, _translate("MainWindow", "Dif. Annualized Premium < "))
        self.lineEdit_o_or_f_instrumet1_9.setItemText(0, _translate("MainWindow", "Set Entry Position"))
        self.lineEdit_o_or_f_instrumet1_9.setItemText(1, _translate("MainWindow", "Difference in % > "))
        self.lineEdit_o_or_f_instrumet1_9.setItemText(2, _translate("MainWindow", "Difference in % < "))
        self.lineEdit_o_or_f_instrumet1_9.setItemText(3, _translate("MainWindow", "Difference in USD > "))
        self.lineEdit_o_or_f_instrumet1_9.setItemText(4, _translate("MainWindow", "Difference in USD < "))
        self.lineEdit_o_or_f_instrumet1_9.setItemText(5, _translate("MainWindow", "Difference in Premium(Annualized) > "))
        self.lineEdit_o_or_f_instrumet1_9.setItemText(6, _translate("MainWindow", "Difference in Premium(Annualized) < "))
        self.lineEdit_o_or_f_instrumet1_10.setItemText(0, _translate("MainWindow", "Set Stop Loss"))
        self.lineEdit_o_or_f_instrumet1_10.setItemText(1, _translate("MainWindow", "Loss in USD"))
        self.lineEdit_o_or_f_instrumet1_10.setItemText(2, _translate("MainWindow", "Loss in BTC/ETH"))
        self.lineEdit_o_or_f_instrumet1_10.setItemText(3, _translate("MainWindow", "Loss in % (Loss)"))
        self.lineEdit_currency_exchange_rate_lower1_4.setText(_translate("MainWindow", "-1000"))
        self.label_18.setText(_translate("MainWindow", "Check Saved Config:"))
        self.pushButton_submit_new_instruments_2.setText(_translate("MainWindow", "UPDATE Settings"))
        self.label_10.setText(_translate("MainWindow", "Settings:"))
        self.lineEdit_o_or_f_instrumet1_2.setItemText(0, _translate("MainWindow", "Future "))
        self.lineEdit_currency_instrumet1_2.setItemText(0, _translate("MainWindow", "Set BTC or ETH:"))
        self.lineEdit_currency_instrumet1_2.setItemText(1, _translate("MainWindow", "BTC"))
        self.lineEdit_currency_instrumet1_2.setItemText(2, _translate("MainWindow", "ETH"))
        self.lineEdit_maturity_instrumet1_2.setDisplayFormat(_translate("MainWindow", "dMMMyy"))
        self.checkBox_perpetual_2.setText(_translate("MainWindow", "PERPETUAL"))
        self.lineEdit_o_or_f_instrumet1_4.setItemText(0, _translate("MainWindow", "Sell"))
        self.lineEdit_o_or_f_instrumet1_4.setItemText(1, _translate("MainWindow", "Buy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_instruments), _translate("MainWindow", "Config"))
        self.textEdit_monitor.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "Monitor"))
        self.pushButton_start_trading.setText(_translate("MainWindow", "START\n"
"ARBITRAGE"))
        self.pushButton_start_print_loglog.setText(_translate("MainWindow", "Start Print"))
        self.label_22.setText(_translate("MainWindow", "BTC Index:"))
        self.label_15.setText(_translate("MainWindow", "Position (USD)"))
        self.label_26.setText(_translate("MainWindow", "Position (BTC/ETH)"))
        self.label_25.setText(_translate("MainWindow", "Mark Price (USD)"))
        self.label_30.setText(_translate("MainWindow", "Profit/Loss"))
        self.label_11.setText(_translate("MainWindow", "Leverage"))
        self.label_12.setText(_translate("MainWindow", "Liquidation Price"))
        self.label_13.setText(_translate("MainWindow", "Average Price"))
        self.label_14.setText(_translate("MainWindow", "Direction"))
        self.pushButton.setText(_translate("MainWindow", "Request\n"
"Account Summary"))
        self.label_16.setText(_translate("MainWindow", "Position (USD)"))
        self.label_27.setText(_translate("MainWindow", "Position (BTC/ETH)"))
        self.label_28.setText(_translate("MainWindow", "Mark Price (USD)"))
        self.label_31.setText(_translate("MainWindow", "Profit/Loss"))
        self.label_19.setText(_translate("MainWindow", "Leverage"))
        self.label_20.setText(_translate("MainWindow", "Liquidation Price"))
        self.label_21.setText(_translate("MainWindow", "Average Price"))
        self.label_23.setText(_translate("MainWindow", "Direction"))
        self.label_24.setText(_translate("MainWindow", "Connection"))
        self.pushButton_stop_arbitrage.setText(_translate("MainWindow", "STOP\n"
"ARBITRAGE"))
        self.lineEdit_13.setText(_translate("MainWindow", "Instruments Difference (USD)"))
        self.lineEdit_14.setText(_translate("MainWindow", "Instruments Dif. Percentage (%)"))
        self.pushButton_2.setText(_translate("MainWindow", "Request Index\n"
"and\n"
"Greeks"))
        self.lineEdit_15.setText(_translate("MainWindow", "Spread AP Expiration 2nd - 1st"))
        self.checkBox_autoScrollBar.setText(_translate("MainWindow", "Auto Scroll Bar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_run_trading), _translate("MainWindow", "Run Arbitrage"))
        self.label_33.setText(_translate("MainWindow", "email: vavarb@protonmail.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Contact"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
